/* data.js — exercise library + seed journey (Waterson 5-2 accumulator, adapted) */

const BUCKETS = ['3-5', '6-8', '9-12', '13-16', '17-20+'];

const CARDIO_MODALITIES = [
  'Run / Sprints', 'Bike', 'Row', 'Stepper',
  'Heavy bag', 'Battle ropes', 'Skipping', 'Plyo circuit',
];

const DAY_TYPES = {
  LEGS1:  { label: 'Legs 1',  kind: 'legs' },
  UPPER1: { label: 'Upper 1', kind: 'upper' },
  SPRINT: { label: 'Sprint',  kind: 'sprint' },
  LEGS2:  { label: 'Legs 2',  kind: 'legs' },
  UPPER2: { label: 'Upper 2', kind: 'upper' },
  MIXED1: { label: 'Mixed',   kind: 'mixed' },
  REST:   { label: 'Rest',    kind: 'rest' },
  // legacy types (v1 journeys / old journal entries)
  MIXED2: { label: 'Mixed 2', kind: 'mixed' },
  ZONE2:  { label: 'Zone 2',  kind: 'zone2' },
};

const SPRINT_MODALITIES = ['Run / Track', 'Bike', 'Row', 'Stepper'];

/* Activation & deactivation repositories — paraphrased ideas in the spirit of
   the Intelligent Fitness bolt-ons. ~10 min before, ~10-15 min after. */
const ACTIVATION_IDEAS = [
  { name: 'Easy cardio, 10 min', text: 'Bike, row or jog at conversational pace. You are raising the heart rate and telling the body work is coming — not training yet.' },
  { name: 'Throw a ball around', text: 'Rugby ball, baseball, anything. Coordination, fun, and the moment to ask yourself: how did I sleep, any niggles, what do I want from today?' },
  { name: 'Skipping', text: '2–3 easy minutes. Rhythm, calves, coordination — a favourite pre-workout switch-on.' },
  { name: 'Dynamic mobility', text: 'Arm circles, leg swings, hip openers, torso rotations. Move every joint you are about to load through its range.' },
  { name: 'Pedal to standing', text: 'From the pike position (hands flat, hips high), pedal the feet one at a time, walk the feet toward the hands, and roll up to standing slowly. Wakes the calves and hamstrings.' },
  { name: 'Plank → pike → cobra', text: 'From a forearm plank, lift the hips to a pike, lower them until they hover, then come forward into a gentle cobra looking slightly up. Spine and abdominals ready.' },
  { name: 'Agility bursts', text: 'Sidesteps, a few light accelerations with controlled deceleration, ten seconds of fast feet. Prime the nervous system, especially before sprint or plyo work.' },
];

/* Concrete dynamic stretches — drawn from the 10-Weeks Wednesday sessions
   plus warm-up standards, filtered for a protected lower back. */
const ACTIVATION_STRETCHES = [
  { name: 'Bear crawl into pigeon', text: 'Hinge down, walk the hands out to a plank. Bring one knee forward and lower toward the floor at 90°, sink onto the forearms, then reach the arms long. Ease out, walk back, stand up. Per side — opens hips and glutes.' },
  { name: 'Bear crawl into cobra', text: 'Walk out to a plank, drop the hips and bring the chest forward into a gentle cobra, looking slightly up. Walk back to standing. Spine extension without load.' },
  { name: 'Reverse lunge + hip-flexor reach', text: 'Step back into a lunge, rear knee down, interlock the fingers and reach overhead with a slight lean back until the hip flexor stretches. Add a small forward-back rock. Per side — the tall-lifter essential.' },
  { name: 'Quad-stretch into reverse lunge', text: 'Standing quad stretch (heel to glute, hold ~30 s), release straight back into a reverse lunge with arms locked overhead, then rise and hug the knee to the chest. One flowing sequence per leg.' },
  { name: "World's greatest stretch", text: 'Long lunge, both hands inside the front foot. Drop the back knee, sink the hips, then rotate the inside arm up to the ceiling, following it with your eyes. Per side — hips, hamstrings and thoracic spine in one move.' },
  { name: 'Leg swings', text: 'Hold something stable. Swing one leg front-to-back 10-15 times, then side-to-side across the body. Loosens hips and hamstrings dynamically — no bouncing at end range.' },
  { name: 'Hip circles / openers', text: 'Standing, lift one knee and draw the biggest circle you can — inward rotations, then outward. Per side.' },
  { name: 'Cat-cow', text: 'On all fours, alternate slowly between rounding the spine up (cat) and letting it sink with the chest forward (cow), moving with the breath. Wakes up every spinal segment gently.' },
  { name: 'Thoracic openers (book drill)', text: 'Kneeling, thread one arm under the body then rotate it up to the ceiling, chest following. Per side. Upper-back rotation so the lower back does not have to provide it later.' },
  { name: 'Spinal mobility rock', text: 'On your back, hug both knees to the chest and rock gently forward and back, growing the range a little each rep. From the Wednesday sessions — a favourite before hinge days.' },
  { name: 'Glutes & piriformis (figure-4)', text: 'On your back, ankle over the opposite knee, clasp behind the thigh and pull toward you until the glute stretches. Per side.' },
  { name: 'Pedal to standing', text: 'Pike position, hands flat, pedal the heels one at a time, walk the feet to the hands and roll up slowly to standing. Calves and hamstrings switched on.' },
  { name: 'Side crab', text: 'In a low squat, crawl sideways a few steps, shoot the trailing leg out, return, and go back the other way. Animalistic movement — ankles, hips and coordination.' },
  { name: 'Upper-body matrix', text: 'Kneeling: cross-body shoulder pull, hands clasped behind the back with chest proud, triceps reach down the spine, wrist circles both ways, and a gentle side neck stretch. ~30 s each.' },
  { name: '90-90 hip switch', text: 'Sitting with both knees bent at 90°, one in front, one to the side, rotate the knees together over to the other side without using the hands. Internal + external hip rotation in one drill.' },
  { name: 'Ankle rockers', text: 'Half-kneeling, front foot flat about a hand-width from a wall. Drive the knee over the toes to touch the wall, heel stays down. Per side — squat depth lives in the ankles.' },
  { name: 'Goblet-squat prying', text: 'Hold the bottom of a light goblet squat and gently shift weight side to side, elbows prying the knees out. 30-45 s. Opens the hips exactly where the squat needs them.' },
];

const DEACTIVATION_IDEAS = [
  { name: 'Bring the heart rate down', text: 'Two or three minutes of easy movement — slow walk, light multidirectional steps. You are switching out of activity mode.' },
  { name: 'Stretch what you trained', text: 'Hold each stretch to a comfortable discomfort, wait for it to fade, then add roughly 10% more and hold again before easing off slowly. Control the exit as much as the entry — stretching marks the end of the session.' },
  { name: 'Breathing reset', text: 'Sit cross-legged, elbows on knees. Breathe into the lower third of the lungs, exhale fully. Ten to fifteen slow breaths — near-meditative, heart rate visibly drops.' },
  { name: 'Ten-second reactivation', text: 'Finish with a ten-second sprint on the spot. It sounds odd after calming down, but it leaves you invigorated for the rest of the day.' },
  { name: 'Refuel window', text: 'The best time to refuel is the 20–30 minutes after training: protein plus fluids. Prepare it before the session so it is waiting for you.' },
];

// measure: 'reps' (log reps + weight) | 'secs' (log seconds + weight)
// pattern: movement family -> pictogram in the Library and workout screens
const SEED_EXERCISES = [
  // legs
  { id: 'box_squat', name: 'Box squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Sit back to the box, drive up through heels',
    desc: 'Box at knee height behind you, bar or dumbbells racked, feet shoulder-width, toes slightly out. Brace the belly, then sit BACK, hips first, taking three seconds down until you sit fully on the box. Shins stay vertical, chest up. No bounce: pause one second staying tight, then drive up fast through the heels. Keep two to three reps in reserve; the set ends when speed drops or form bends. As slot A: ramp lighter in rounds 1–2, working weight rounds 3–5.' },
  { id: 'paused_box_squat', name: 'Paused box squat', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'squat',
    cue: '2s pause on the box, no bounce',
    desc: 'A box squat with a full two-second sit: on the box, everything stays tight and the weight never rests. Then stand up as fast as you can. The pause deletes all momentum, so this is pure strength. Expect noticeably less weight than your normal box squat.' },
  { id: 'reverse_lunge', name: 'Reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Knee kisses the floor, per leg',
    desc: 'Hold a dumbbell at the chest (goblet) or stand free. Take a LONG step back, feet on railway tracks, not a tightrope, and lower for two seconds until the back knee touches the floor softly. Torso stays vertical, front shin vertical. Push hard through the front heel to stand. Hold something stable with one hand at first; that is technique, not cheating. Per leg.' },
  { id: 'deficit_reverse_lunge', name: 'Deficit reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Front foot on low plate, per leg',
    desc: 'A reverse lunge with the front foot on a low plate or step (5–10 cm) for extra depth and a bigger glute stretch. Two seconds down, back knee just below foot level, then drive up through the front heel. Torso stays tall the whole rep. Per leg.' },
  { id: 'goblet_squat', name: 'Goblet squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Elbows inside knees at depth',
    desc: 'Hold one dumbbell or kettlebell vertically against the chest, elbows pointing down. Feet shoulder-width, toes slightly out. Sit down for two to three seconds until the elbows lightly brush the inside of the knees. Chest up, heels down. Stand up strong and squeeze the glutes at the top.' },
  { id: 'trap_bar_deadlift', name: 'Trap bar deadlift', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'hinge',
    cue: 'Neutral grip, push the floor away, no rounding',
    desc: 'Stand in the middle of the bar, feet hip-width. Grip the high handles with straps on anything heavy: the grip quits long before the legs do. Chest up, back long, big breath, brace hard, then push the floor away until you stand fully tall. Squeeze the glutes at the top, no lean-back. Lower in two seconds with the same flat back. Keep two to three reps in reserve: the set ends when bar speed drops, the back rounds, or the knees cave, whichever comes first. As slot A: ramp rounds 1–2, working weight rounds 3–5. If the pull feels deep, raise the plates on blocks.' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian split squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Rear foot on bench, per leg',
    desc: 'Rear foot laces-down on a bench, front foot about two steps ahead. Lower straight down for two seconds until the front thigh is parallel to the floor. A slight forward lean is fine; the front heel stays planted. Drive up through that heel. Per leg.' },
  { id: 'lateral_lunge', name: 'Lateral lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Sit into the working hip, per leg',
    desc: 'Take one wide step to the side. Sit back into that hip for two seconds, knee tracking over the foot, the other leg straight, both heels down. Start with bodyweight and half depth, and earn more range over the weeks before adding load. Push off hard back to standing. Per leg.' },
  { id: 'romanian_deadlift', name: 'Romanian deadlift', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Hinge, soft knees, flat back',
    desc: 'Start standing, weight against the thighs, knees soft. Push the hips straight back and lower the weight slowly, three seconds, sliding it down the legs only as far as a flat back allows, mid-shin at most. The hamstrings should pull hard. Drive the hips forward to stand and squeeze the glutes at the top. Range is earned over weeks. It is a hip movement, never a back lift.' },
  { id: 'single_leg_rdl', name: 'Single-leg RDL', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Square hips, per leg',
    desc: 'Stand on one leg, weight in the opposite hand. Hinge forward slowly as the free leg extends straight behind you. Hips stay level, back flat. Lower until the hamstring pulls, then squeeze the glute to stand tall. Touch the free toe down between reps if balance wobbles. Per leg.' },
  { id: 'hip_thrust', name: 'Hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'Shoulders on bench, squeeze glutes at top',
    desc: 'Shoulder blades on a bench, feet flat under the knees, weight on the hips. Lower the hips almost to the floor, then drive up through the heels until the body is one straight line from knees to shoulders. At the top, tuck the tailbone slightly and squeeze the glutes hard for two seconds. Chin tucked, ribs down; never arch the lower back. Lower with control.' },
  { id: 'single_leg_hip_thrust', name: 'Single-leg hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'One foot down, per leg',
    desc: 'A hip thrust with one foot down and the other leg held straight. Same rules: drive through the heel, keep the hips level, hold the two-second squeeze at the top, no back arch. Per leg.' },
  { id: 'box_step_up', name: 'Box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Step up both feet, step down — never jump down',
    desc: 'Face a knee-high box. Step up and press through the WHOLE foot of the top leg; do not push off the bottom leg. Stand fully tall on the box, then step down slowly, two seconds. Never jump down. All reps leading with one leg, then switch.' },
  { id: 'lateral_box_step', name: 'Lateral box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Sideways to the box, per leg',
    desc: 'Stand side-on to the box. Step up with the near leg, driving through its heel until you stand tall on top, then lower back down slowly on the same side. The top leg does all the work; the bottom leg comes along. Per leg.' },
  { id: 'calf_raise', name: 'Calf raise', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Full stretch at bottom, pause at top',
    desc: 'Balls of the feet on an edge, heels hanging free. Lower for two seconds into a full stretch and pause briefly. Then rise as high as possible onto the toes and squeeze one second at the top. No bouncing: the slow stretch at the bottom is where the growth signal lives.' },
  { id: 'jump_squat', name: 'Jump squat', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Land soft, reset each rep',
    desc: 'Sit into a quarter squat, arms swung back, then jump as high as you can with the hips fully opening. Land softly, toes first, knees bent, and come to a complete stop. Reset the stance, then jump again. Every jump maximal, every landing quiet.' },
  { id: 'band_lateral_walk', name: 'Band lateral walk', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Band above knees, small squat steps',
    desc: 'Loop band just above the knees. Quarter-squat, toes forward. Step sideways with slow, deliberate steps, leading with the knee, and never let the feet come together, so the band stays tight the whole time. You should feel the outside of the hips working. Count steps in each direction.' },
  { id: 'band_matrix', name: 'Band matrix', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Side steps + forward/back, keep band tension',
    desc: 'Band above the knees, tension never drops. Slow side steps to the right, then to the left, then small steps forward and back, knees pushed out against the band throughout. Steady pace, never rushed. One full circuit is one rep.' },
  { id: 'wall_sit', name: 'Wall sit', group: 'legs', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Knees at 90°, back flat on wall',
    desc: 'Back flat against the wall. Slide down until the thighs are parallel and the knees sit at 90° directly above the ankles. Hands off the legs, breathe continuously, never hold the breath. Best done FRESH on non-leg days, several two-minute holds; start shallower and progress the angle over weeks. Logged in seconds.' },
  { id: 'slider_leg_curl', name: 'Slider leg curl', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'Bridge up, curl the heels in, hips stay high',
    desc: 'On your back, heels on sliders, a towel on smooth floor, or a Swiss ball. Bridge the hips up and keep them up. Curl the heels toward the glutes for two seconds, then push them slowly back out over three seconds without the hips dropping. The best hamstring builder without a machine. Shorten the range before you let the hips sag.' },
  { id: 'seated_calf_raise', name: 'Seated calf raise', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Knees bent 90°, weight on thighs, slow stretch',
    desc: 'Sit on a bench, balls of the feet on a plate or step, dumbbells resting on the thighs. With the knees bent at 90°, lower the heels for two seconds into a full stretch, pause, then rise onto the toes and squeeze one second. The bent knee shifts the work to the soleus, which sets your ankle mobility and squat depth.' },
  { id: 'spanish_squat', name: 'Spanish squat', group: 'legs', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Band behind the knees, sit back, hold',
    desc: 'Loop a strong band behind the knees, anchored low in front of you. Lean back against it and sit into a squat with vertical shins, thighs near parallel. Hold, breathing steadily the whole time. High quad work with very little kneecap pressure, which is exactly the point. Logged in seconds.' },
  // upper
  { id: 'pull_up', loadable: true, name: 'Pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Full hang to chin over bar',
    desc: 'Dead hang, hands just wider than the shoulders, palms away. Pull the elbows down toward the ribs until the chin clears the bar, chest moving toward the bar, no swinging. Lower all the way to straight arms in two to three seconds; the slow lowering builds half the strength. The kg field = added weight (belt or DB between the feet); 0 = bodyweight.' },
  { id: 'weighted_pull_up', name: 'Weighted pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Add belt/dumbbell, strict form',
    desc: 'A pull-up with load on a dip belt or a dumbbell between the feet. Same standard: dead hang to chin over bar, two-to-three-second lowering, no kip. As an anchor: bodyweight in round 1, add load from round 2. Log the added weight.' },
  { id: 'chin_up', loadable: true, name: 'Chin-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Underhand grip, full range',
    desc: 'A pull-up with the palms toward you, hands shoulder-width. More biceps and usually a rep or two more than pull-ups. Same standard: full hang, chin over bar, slow lowering. The kg field = added weight; 0 = bodyweight.' },
  { id: 'db_bench_press', name: 'DB bench press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Full range, elbows ~45°',
    desc: 'Flat on the bench, feet planted, shoulder blades pinched back and down. Lower the dumbbells for two to three seconds to chest level, elbows about 45° from the body. Press up and slightly together to straight arms. The slow lowering is what protects the shoulders.' },
  { id: 'bench_press', name: 'Bench press', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Bar to chest, feet planted',
    desc: 'Feet planted, shoulder blades pinched, slight arch. Lower the bar under control, two to three seconds, to the lower chest. Touch lightly, no bounce, then press to lockout. Use a spotter or safety pins when the weight is heavy.' },
  { id: 'incline_db_press', name: 'Incline DB press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Bench ~30°, press up and slightly back',
    desc: 'Bench at about 30°. Lower the dumbbells for two seconds to the upper chest, elbows 45°, then press up and slightly back so they finish over the collarbones. Squeeze at the top without banging the weights together.' },
  { id: 'push_up', name: 'Push-up', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Elbows to 90°, neutral back',
    desc: 'Hands under the shoulders (on dumbbells for straight wrists and extra depth). Body one rigid line: glutes and belly squeezed. Lower the chest for two seconds to a fist-height above the floor, elbows about 45°, then push the floor away to straight arms. The hips never sag and never pike.' },
  { id: 'overhead_press', name: 'Overhead press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Press strict, ribs down',
    desc: 'Standing, weight at the shoulders. Squeeze the glutes, ribs down, then press strictly overhead until the arms lock and the biceps end up beside the ears. Move the head slightly back to let the bar pass, then push it through. Lower back to the shoulders in two seconds. No leg drive, no lean-back.' },
  { id: 'arnold_press', name: 'Arnold press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Rotate palms through the press',
    desc: 'Start with the dumbbells at shoulder height, palms facing you. Press up while rotating the palms to face forward, finishing locked out overhead. Reverse the rotation slowly on the way down, three seconds. Light weight, constant tension, strict form.' },
  { id: 'bent_over_row', name: 'Bent-over row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Hinge, pull to lower ribs',
    desc: 'Hinge to about 45°, back flat, knees soft. Row the weight to the lower ribs leading with the elbows and squeeze the shoulder blades one second. Lower for two seconds without dropping the chest. If the lower back tires before the lats do, use the chest-supported row instead.' },
  { id: 'single_arm_row', name: 'Single-arm DB row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Knee on bench, per arm',
    desc: 'One knee and one hand on the bench, back flat and level like a table. Row the dumbbell to the hip in an arc, elbow close to the body. Squeeze one second at the top, lower for two seconds into a full stretch. Do not rotate the torso to lift more. Per arm.' },
  { id: 'chest_supported_row', name: 'Chest-supported DB row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Chest on incline bench, row both DBs',
    desc: 'Lie chest-down on an incline bench, dumbbells hanging. Row both to the hips, driving the elbows back, and squeeze the shoulder blades together for one second. Lower to a full stretch in two seconds. The bench removes the lower back completely, so there is no way to cheat.' },
  { id: 'shoulder_matrix', name: 'Shoulder matrix', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Lateral + front raises, soft elbows',
    desc: 'Light dumbbells. Raise to the side to exactly shoulder height with soft elbows, lower slowly. Then straight into a front raise to shoulder height, lower slowly. One pair is one rep. If you have to swing, the weight is too heavy.' },
  { id: 'lateral_raise', name: 'Lateral raise', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'To shoulder height, no swing',
    desc: 'Dumbbells at the sides, elbows slightly bent. Raise out to shoulder height and no higher, leading with the elbows as if pouring water from a jug. Pause a beat, then lower for three seconds. The slow lowering IS the exercise. Keep it light and strict.' },
  { id: 'dips', loadable: true, name: 'Dips', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Elbows to 90°, lean slightly forward',
    desc: 'On the bars, shoulders pressed down away from the ears. Lean slightly forward, lower for two seconds until the elbows reach 90° (upper arms parallel to the floor), then press back to straight arms. Go no deeper if the shoulders pinch. The kg field = added weight; 0 = bodyweight.' },
  { id: 'weighted_dip', name: 'Weighted dip', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Add weight, full depth',
    desc: 'Dips with a belt or a dumbbell between the feet. Same depth standard: elbows to 90°, two-second lowering, full lockout at the top. Log the added weight.' },
  { id: 'face_pull', name: 'Band face pull', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull',
    cue: 'Band to face, elbows high',
    desc: 'Band anchored at face height: door anchor or the pull-up bar. Pull toward the bridge of the nose with the elbows high and wide, finishing with the hands beside the ears and the upper back squeezed for one second. Return in three seconds and let the shoulder blades slide apart. Tall posture; if the head pokes forward, take a lighter band.' },
  // core
  { id: 'ab_rollout', name: 'Ab rollout', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Roll out slow, no sag',
    desc: 'Kneel with the wheel or loaded bar under the shoulders. Brace the belly as if about to take a punch and tuck the tailbone. Roll out slowly, three seconds, only as far as the hips stay perfectly level. Pull back with the abs, not the arms. Shorten the range before you ever let the lower back arch.' },
  { id: 'hanging_knee_raise', name: 'Hanging knee raise', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Knees to chest, no swing',
    desc: 'Hang from the bar with active shoulders. Curl the knees up to the chest and tilt the pelvis at the very top; that tilt is where the abs actually work. Lower for three seconds to a dead stop. No swinging between reps. Straight legs to progress.' },
  { id: 'plank_to_pike', name: 'Plank to pike', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Forearms down, hips up and back',
    desc: 'Forearm plank, body one line. Push the hips up and back into a pike, an upside-down V, hold one beat, then return to a tight plank without any sag. Slow and controlled in both directions.' },
  { id: 'pallof_press', name: 'Pallof press', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Resist rotation, per side',
    desc: 'Band or cable at chest height, stand side-on, feet hip-width. Hold the handle at the sternum, press it straight out and hold two seconds. The pull tries to twist you; your job is not to move at all. Return under control. Per side.' },
  { id: 'v_up', name: 'V-up', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Hands to feet, control down',
    desc: 'Lie flat, arms overhead. In one motion lift straight legs and torso, reaching the hands to the feet at the top. Lower BOTH halves slowly, three seconds, stopping just above the floor. If the lower back complains, switch to dead bugs.' },
  { id: 'dead_bug', name: 'Dead bug', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Lower back pressed to floor, opposite arm + leg',
    desc: 'On your back, arms straight up, knees bent 90° over the hips. Press the lower back into the floor and keep it there for the whole set; that is the entire exercise. Lower one arm and the opposite leg toward the floor over three seconds, stopping the moment the back starts to lift. Exhale as the limbs lower, return, switch. Per side.' },
  { id: 'bird_dog', name: 'Bird dog', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'On all fours, opposite arm + leg, no wobble',
    desc: 'On hands and knees, back level. Reach one arm long and the opposite leg back until both are level with the torso. Hips stay square; nothing wobbles or tilts. Hold ten seconds while breathing normally, then sweep elbow and knee together under the body and reach out again. Long, perfectly still holds are the point. Per side.' },
  { id: 'mcgill_curl_up', name: 'McGill curl-up', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Hands under lower back, lift head + shoulders only',
    desc: 'On your back: one knee bent, one leg straight, hands under the natural arch of the lower back. Lift only the head and shoulders a few centimetres; the spine does not bend, the abs simply switch on hard. Hold ten seconds, breathing normally, then lower slowly. Swap the bent leg halfway through the set.' },
  { id: 'mountain_climbers', name: 'Mountain climbers', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Fast knees, flat back',
    desc: 'High plank, hands under the shoulders, hips level with the shoulders. Drive the knees toward the chest alternately, as fast as clean form allows. The hips stay down; the moment they start bouncing, slow down. Logged in seconds.' },
  { id: 'bear_crawl', name: 'Bear crawl', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Knees an inch off the floor',
    desc: 'On hands and toes, knees bent one inch off the floor, back flat like a tabletop. Crawl forward with opposite hand and foot moving together, small steps, hips level. Crawl backward the same way. Logged in seconds.' },
  // mixed / plyo / full-body
  { id: 'box_jump', name: 'Box jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Explode up, step down',
    desc: 'Stand one short step from the box. Dip into a quarter squat, throw the arms, and jump explosively. Land SOFTLY on the box: both feet flat, knees bent, quiet landing. Stand fully tall on top, then STEP down; never jump down. Full reset and pause before every rep, so each jump starts from a dead stop.' },
  { id: 'broad_jump', name: 'Broad jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Stick the landing, walk back',
    desc: 'Dip, swing the arms back, then jump forward as far as you can. Stick the landing in a quarter squat and hold it one second; a clean landing counts for more than distance. Walk back, reset completely, jump again.' },
  { id: 'kb_swing', name: 'Kettlebell swing', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'swing',
    cue: 'Hips drive, arms relaxed',
    desc: 'Hinge, never squat. Hike the kettlebell back high between the legs, then SNAP the hips forward hard so the bell floats to chest height on straight-ish arms. Squeeze the glutes at the top, belly braced; the arms only steer. Let it swing straight back into the next hike. The power is one hundred percent hips.' },
  { id: 'kb_clean_press', name: 'KB clean & press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Clean to rack, press strict, per arm',
    desc: 'Swing the kettlebell up so it lands softly in the rack at the shoulder; it should roll around the wrist, not bang it. Pause one beat, then press strictly overhead to lockout. Lower to the shoulder, then back into the swing. Per arm.' },
  { id: 'thruster', name: 'Thruster', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Squat into overhead press, one motion',
    desc: 'Dumbbells at the shoulders. Squat to parallel with the chest up, then drive up fast and let that momentum carry the weights straight overhead in one continuous motion, finishing with biceps by the ears. Lower to the shoulders with control as you sink into the next squat. Big movement, big heart rate.' },
  { id: 'db_snatch', name: 'DB snatch', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Floor to overhead, per arm',
    desc: 'One dumbbell on the floor between the feet. Hinge, grip, then jump the weight upward in one explosive pull, punching it out to a straight arm overhead with no pause at the shoulder. Stand fully tall, then lower it in two steps: to the shoulder, then to the floor. Per arm.' },
  { id: 'devil_press', name: 'Devil press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Burpee + double-DB snatch',
    desc: 'Two dumbbells. Burpee down with the hands on the bells, chest to the floor, jump the feet back in, then swing both dumbbells between the legs and up overhead in one motion. Finish locked out and tall. Brutal by design; pick a pace you can hold for the whole set.' },
  { id: 'burpee', name: 'Burpee', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Chest to floor, jump at top',
    desc: 'Hands to the floor, jump or step the feet back, chest touches the floor. Push up fast, jump the feet back in under the hips, then stand and finish with a small jump and the hips fully open at the top. A smooth, quick rhythm beats frantic speed.' },

  { id: 'incline_triceps_ext', name: 'Incline triceps extension', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Upper arms frozen, stretch behind the head',
    desc: 'Lie back on a low incline (15\u201330\u00b0), a dumbbell in each hand pressed over the chest, upper arms angled slightly back toward the head. Keep the upper arms frozen: bend only the elbows and lower the weights behind the head for three seconds until you feel a clear stretch in the triceps. Press back to straight arms and squeeze the triceps for one second. If the upper arms drift forward, the tension leaves the muscle.' },
  { id: 'incline_db_fly', name: 'Incline dumbbell fly', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Soft elbows, hug a barrel',
    desc: 'On an incline bench (30\u201345\u00b0), dumbbells over the upper chest, palms facing each other, elbows fixed at a slight bend. Open the arms out in three seconds until you feel the stretch across the chest, and no deeper. Sweep back up in a wide arc, as if hugging a barrel, and squeeze the upper chest for one second at the top. Aching shoulders mean the arc is too deep or the elbows too straight.' },
  { id: 'chest_supported_y_raise', name: 'Y raise (chest-supported)', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Thumbs up, arms to the ears, no shrug',
    desc: 'Chest down on an incline bench, light dumbbells hanging, thumbs pointing up. Raise the arms up and forward into a Y in two seconds until they line up with the ears. Hold one second at the top: the squeeze belongs low between the shoulder blades, never in the neck. Lower in three seconds. Go lighter than feels serious; the moment you swing, the weight is too heavy.' },
  { id: 'plyo_push_up', name: 'Plyo push-up', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Hands leave the floor, land soft',
    desc: 'Push-up position, hands under the shoulders, body one rigid line. Lower with control, then drive up so explosively that the hands leave the floor. Land on soft elbows and sink straight into the next rep. Stop the set the moment the hands stop leaving the floor: slow reps defeat the point of this exercise. Hands on a bench is the easier version; build there first.' },
  { id: 'nordic_curl', name: 'Nordic curl', group: 'legs', measure: 'reps', bucket: '3-5', pattern: 'bridge',
    cue: 'Hips straight, fall slowly, catch with hands',
    desc: 'Kneel on a pad, ankles locked under a bench or a loaded bar. From tall knees with the hips fully straight, lower the whole body forward as slowly as you can: fight for five seconds or more, hands ready to catch at the bottom. Push off the floor lightly and pull back up with the hamstrings as much as they allow. Folding at the hips is the rep gone wrong. Three slow reps beat ten fast falls.' },
  { id: 'skull_crusher', name: 'Skull crusher', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Elbows still, lower past the forehead',
    desc: 'Lie on a flat bench, dumbbells or an EZ bar pressed above the chest, arms vertical. Keep the upper arms frozen: bend the elbows and lower the weight toward the forehead, or just past it toward the bench, for three seconds. Press back to straight arms and squeeze the triceps for one second. If the elbows ache, aim the weight slightly behind the head and drop the load a step.' },
  { id: 'zottman_curl', name: 'Zottman curl', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Curl palms up, lower palms down',
    desc: 'Standing, dumbbells at the sides, palms forward. Curl up in two seconds and squeeze at the top. There, rotate the palms to face down and lower in four seconds; the slow palms-down descent is the whole point of this exercise. Rotate back at the bottom and repeat. Elbows stay pinned to the ribs; no swinging from the hips.' },
  { id: 'sissy_squat', name: 'Sissy squat', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'squat',
    cue: 'Knees forward, torso back, shallow first',
    desc: 'Hold an upright (rack or door frame) with one hand and rise onto the balls of the feet. Bend the knees and drive them forward while the torso leans back, keeping one straight line from knees to shoulders. Lower for three seconds, only as far as the knees accept without complaint, pause one second, and return by squeezing the quads. This exercise loads the knees hard: start shallow, add depth over weeks, and skip it on any day the knees feel irritated.' },
  { id: 'squat_jump', name: 'Squat jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Sit, explode up, land quiet',
    desc: 'Feet shoulder-width, no weight needed. Sit into a half squat for two seconds, arms swung back, then jump straight up as high as you can with the arms driving. Land softly back in the half squat, heels touching down quietly. Pause and fully reset before the next rep: every jump starts from a dead stop, never from a bounce.' },
  { id: 'weighted_glute_kickback', name: 'Glute kickback (weighted)', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'bridge',
    cue: 'Heel to ceiling, squeeze two seconds',
    desc: 'On all fours, a dumbbell folded into the crease behind one knee, or a band around the foot. Keep the knee bent at 90\u00b0 and drive the heel toward the ceiling in two seconds, until the thigh lines up with the torso and no higher; past that, the lower back takes over. Squeeze the glute hard for two seconds at the top, then lower in three seconds without the knee touching down. All reps on one side, then switch. The back stays flat; only the hip moves.' },  { id: 'sprawl', name: 'Sprawl', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Burpee without push-up or jump',
    desc: 'The fast burpee: hands down, shoot the legs back to a plank, snap them back in, stand tall. No push-up and no jump; that is exactly what keeps the pace high. The chest stays over the hands.' },
  { id: 'box_jump_over', name: 'Box jump-over', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Jump on, step over and down',
    desc: 'Jump explosively onto the box and land soft. Step over the far edge and down with control, turn around, repeat the other way. One crossing is one rep. Always step down from the top, never jump.' },
  { id: 'walking_lunge', name: 'Walking lunge', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Long steps, torso tall, total steps',
    desc: 'Lunge forward until the back knee kisses the floor, then push through the front heel and step STRAIGHT through into the next lunge with no pause between reps. Torso tall, steps long. Count total steps.' },
  { id: 'renegade_row', name: 'Renegade row', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Plank on DBs, row without twisting',
    desc: 'High plank with the hands on two dumbbells, feet set wide. Row one bell to the hip while the rest of the body stays dead still: hips level, zero twist. The plank is the real exercise. Lower with control, then alternate arms. Slow rows beat fast wobbly ones.' },
  { id: 'farmers_carry', name: "Farmer's carry", group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'Heavy DBs, tall posture',
    desc: 'Pick up the heaviest dumbbells you can hold with good posture: stand tall, shoulders back and down, ribs stacked over hips. Walk with short quick steps, eyes forward. The moment posture cracks, set them down; the set is over. Logged in seconds.' },
  { id: 'suitcase_carry', name: 'Suitcase carry', group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'One-sided carry, stay level, per side',
    desc: 'One heavy dumbbell on one side. Walk tall and perfectly level with no lean to either side; the core fights the tilt the entire time. Shoulders square, free arm relaxed. Swap sides halfway. Logged in seconds per side.' },
  // travel: band + bodyweight library (1 long band with door anchor + 1 loop band)
  { id: 'band_squat', name: 'Band squat', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'squat', travel: true,
    cue: 'Stand on the band, handles at shoulders',
    desc: 'Stand on the long band, feet shoulder-width, a handle at each shoulder. Squat down for two seconds until the thighs are parallel, chest up, then drive up against the band and squeeze the glutes at the top. Log band level instead of kg.' },
  { id: 'split_squat', name: 'Split squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Static lunge stance, per leg',
    desc: 'A static lunge: one foot forward, one behind, feet hip-width apart for balance. Lower straight down for two seconds until the back knee nearly touches the floor, then drive up through the front heel. The feet never move; that is what makes it different from a lunge. Rear foot on a chair turns it Bulgarian. Per leg.' },
  { id: 'band_rdl', name: 'Band RDL', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'hinge', travel: true,
    cue: 'Stand on band, hinge against it',
    desc: 'Stand on the long band, handles at the thighs. Push the hips straight back with a flat back, lowering the hands along the legs until the hamstrings pull. Then stand tall against the band and squeeze the glutes. Slow on the way down, strong on the way up.' },
  { id: 'glute_bridge', name: 'Glute bridge', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'bridge',
    cue: 'Shoulders on floor, squeeze at top',
    desc: 'On your back, knees bent, feet flat under the knees. Drive through the heels and lift the hips until the body is straight from knees to shoulders. Squeeze the glutes hard for two seconds at the top; do not push the lower back into an arch. Lower with control. Loop band above the knees for more.' },
  { id: 'single_leg_glute_bridge', name: 'Single-leg glute bridge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'One foot down, per leg',
    desc: 'A glute bridge on one foot, the other leg held straight and in line with the body. The hips must stay level; if one side drops, slow down. Hold the two-second squeeze at the top. Per leg.' },
  { id: 'band_row', name: 'Band row', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull', travel: true,
    cue: 'Anchor at chest height, squeeze blades',
    desc: 'Long band anchored at chest height in the door, or around the feet if seated. Sit or stand tall, row the handles to the lower ribs, squeeze the shoulder blades one second, then return in two seconds keeping tension the whole way. Chest stays proud.' },
  { id: 'band_pulldown', name: 'Band pulldown', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull', travel: true,
    cue: 'Anchor high, pull to chest',
    desc: 'Long band anchored over the top of the door. Kneel, arms up, chest proud. Pull the handles down to the collarbones by driving the elbows to the ribs. Squeeze one second, release slowly over three seconds. The hotel pull-up.' },
  { id: 'band_pull_apart', name: 'Band pull-apart', group: 'upper', measure: 'reps', bucket: '17-20+', pattern: 'pull', travel: true,
    cue: 'Arms straight, band to chest',
    desc: 'Hold the band at shoulder height, arms straight, hands shoulder-width. Pull it apart until it touches the chest, squeezing the shoulder blades together for one second. Return in two seconds; never let it snap back. Small movement, big posture payoff.' },
  { id: 'band_chest_press', name: 'Band chest press', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push', travel: true,
    cue: 'Band around the back, press forward',
    desc: 'Long band across the upper back, a handle in each hand, split stance. Press forward to straight arms, squeeze one second, return in two seconds. The band pulls hardest at lockout, so the return needs the most control.' },
  { id: 'chair_dip', name: 'Chair dip', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push', travel: true,
    cue: 'Hands on chair edge, elbows to 90°',
    desc: 'Hands on the front edge of a solid chair, fingers forward, legs out. Lower the hips for two seconds until the elbows reach 90°, back staying close to the chair, then press up to straight arms. Shoulders stay down away from the ears. Bend the knees to make it easier.' },
  { id: 'band_overhead_press', name: 'Band overhead press', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'press', travel: true,
    cue: 'Stand on band, press strict',
    desc: 'Stand on the long band, handles at the shoulders. Ribs down, glutes tight. Press straight up to locked arms, then resist the band back down for two to three seconds.' },
  { id: 'band_lateral_raise', name: 'Band lateral raise', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise', travel: true,
    cue: 'Stand on band, raise to shoulder height',
    desc: 'Stand on the band, handles at the sides, elbows slightly bent. Raise out to shoulder height, pause, then lower against the band for three seconds. That slow lowering is the point.' },
  { id: 'band_thruster', name: 'Band thruster', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'press', travel: true,
    cue: 'Squat into overhead press, one motion',
    desc: 'Stand on the long band, handles at the shoulders. Squat to parallel, then drive up fast and press overhead in one continuous motion, locking out against the band. Control the slow return to the shoulders as you sink into the next rep.' },
  { id: 'walkout', name: 'Walkout', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Hands walk out to plank, no sag',
    desc: 'From standing, hinge and place the hands on the floor. Walk them out to a long plank, hips level and belly braced, pause one second, then walk back and stand tall. Reach a hand-length further as you get stronger, but always stop short of any hip sag.' },
  { id: 'plank_hold', name: 'Plank hold', group: 'core', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'One straight line, braced',
    desc: 'Forearms down, elbows under the shoulders. Squeeze the glutes and belly so the body forms one rigid line from heels to head. No sag, no pike. When the line breaks, the set is over; only quality seconds count. Logged in seconds.' },
  { id: 'side_plank', name: 'Side plank', group: 'core', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Hips high, per side',
    desc: 'On one forearm, elbow under the shoulder, feet stacked. Lift the hips until the body is one straight line, then push them slightly up and forward and hold, breathing normally. Several short perfect holds beat one long shaky one. Logged in seconds per side.' },
];

/* Travel mode: gym exercise -> band/bodyweight substitute (same movement pattern).
   Exercises not listed are already hotel-compatible and stay as they are. */
const TRAVEL_SUBS = {
  box_squat: 'band_squat', paused_box_squat: 'band_squat', goblet_squat: 'band_squat',
  trap_bar_deadlift: 'band_rdl',
  deficit_reverse_lunge: 'reverse_lunge', bulgarian_split_squat: 'split_squat',
  box_step_up: 'walking_lunge', lateral_box_step: 'lateral_lunge',
  romanian_deadlift: 'band_rdl',
  hip_thrust: 'glute_bridge', single_leg_hip_thrust: 'single_leg_glute_bridge',
  pull_up: 'band_pulldown', weighted_pull_up: 'band_pulldown', chin_up: 'band_pulldown',
  bent_over_row: 'band_row', single_arm_row: 'band_row', renegade_row: 'band_row', chest_supported_row: 'band_row',
  face_pull: 'band_pull_apart',
  db_bench_press: 'push_up', bench_press: 'push_up', incline_db_press: 'push_up',
  incline_db_fly: 'band_chest_press',
  dips: 'chair_dip', weighted_dip: 'chair_dip',
  overhead_press: 'band_overhead_press', arnold_press: 'band_overhead_press',
  shoulder_matrix: 'band_lateral_raise', lateral_raise: 'band_lateral_raise',
  ab_rollout: 'walkout', hanging_knee_raise: 'v_up',
  box_jump: 'jump_squat', broad_jump: 'jump_squat', box_jump_over: 'sprawl',
  kb_swing: 'jump_squat', kb_clean_press: 'band_thruster', thruster: 'band_thruster', db_snatch: 'band_thruster',
  devil_press: 'burpee',
  farmers_carry: 'plank_hold', suitcase_carry: 'side_plank',
  seated_calf_raise: 'calf_raise',
};

const TRAVEL_CARDIO = ['Skipping', 'Shadow boxing', 'Burpees', 'High knees', 'Stair runs', 'Running'];
const TRAVEL_SPRINT_MODALITIES = ['Stair runs', 'Burpees', 'Shadow boxing', 'High knees'];

// Slot order = accumulator frequency: A done 5x per session, B 4x ... E 1x.
// A/B = anchor lifts. Weeks 1-3 (early) and 4-6 (late) blocks.
const SEED_BLOCKS = {
  early: {
    LEGS1:  ['box_squat', 'reverse_lunge', 'slider_leg_curl', 'seated_calf_raise', 'lateral_lunge'],
    UPPER1: ['pull_up', 'db_bench_press', 'overhead_press', 'chest_supported_row', 'ab_rollout'],
    MIXED1: ['box_jump', 'kb_swing', 'thruster', 'plank_to_pike', 'farmers_carry'],
    LEGS2:  ['trap_bar_deadlift', 'box_squat', 'slider_leg_curl', 'hip_thrust', 'farmers_carry'],
    UPPER2: ['incline_db_press', 'chin_up', 'dips', 'shoulder_matrix', 'face_pull'],
    MIXED2: ['burpee', 'walking_lunge', 'renegade_row', 'db_snatch', 'mountain_climbers'],
  },
  late: {
    LEGS1:  ['paused_box_squat', 'bulgarian_split_squat', 'single_leg_rdl', 'seated_calf_raise', 'lateral_lunge'],
    UPPER1: ['weighted_pull_up', 'bench_press', 'arnold_press', 'single_arm_row', 'hanging_knee_raise'],
    MIXED1: ['broad_jump', 'kb_clean_press', 'db_snatch', 'mcgill_curl_up', 'suitcase_carry'],
    LEGS2:  ['trap_bar_deadlift', 'box_squat', 'romanian_deadlift', 'slider_leg_curl', 'hip_thrust'],
    UPPER2: ['weighted_dip', 'chin_up', 'incline_db_fly', 'lateral_raise', 'pallof_press'],
    MIXED2: ['devil_press', 'box_jump_over', 'sprawl', 'dead_bug', 'bear_crawl'],
  },
};

const WEEK_PLAN = ['LEGS1', 'UPPER1', 'MIXED1', 'LEGS2', 'UPPER2', 'SPRINT', 'REST'];

function seedState() {
  const exercises = {};
  SEED_EXERCISES.forEach((e) => { exercises[e.id] = Object.assign({}, e); });
  return {
    version: STORE_VERSION,
    settings: { cardioMinutes: 2, fontScale: 1, weightStep: 2.5, travelMode: false },
    exercises,
    journeys: [{
      id: 'j1',
      name: 'Journey 1',
      startDate: localDate(),
      weekCount: 6,
      weekPlan: WEEK_PLAN.slice(),
      blocks: JSON.parse(JSON.stringify(SEED_BLOCKS)),
    }],
    activeJourneyId: 'j1',
    sessions: [],
    zone2Checks: {},
    bigThree: {},
    current: null,
  };
}

function blockForWeek(week) { return week <= 3 ? 'early' : 'late'; }
