/* data.js — exercise library + seed journey (Waterson 5-2 accumulator, adapted) */

const BUCKETS = ['6-8', '9-12', '13-16', '17-20+'];

const CARDIO_MODALITIES = [
  'Run / Sprints', 'Bike', 'Row', 'Stepper',
  'Heavy bag', 'Battle ropes', 'Skipping', 'Plyo circuit',
];

const ZONE2_MODALITIES = ['Bike', 'Run', 'Row', 'Walk / Hike', 'Stepper', 'Swim'];

const DAY_TYPES = {
  LEGS1:  { label: 'Legs 1',  kind: 'legs' },
  UPPER1: { label: 'Upper 1', kind: 'upper' },
  SPRINT: { label: 'Sprint',  kind: 'sprint' },
  LEGS2:  { label: 'Legs 2',  kind: 'legs' },
  UPPER2: { label: 'Upper 2', kind: 'upper' },
  MIXED1: { label: 'Mixed',   kind: 'mixed' },
  REST:   { label: 'Rest',    kind: 'rest' },
  // legacy types (v1 journeys / old journal entries)
  MIXED2: { label: 'Mixed 2', kind: 'mixed' },
  ZONE2:  { label: 'Zone 2',  kind: 'zone2' },
};

const SPRINT_MODALITIES = ['Run / Track', 'Bike', 'Row', 'Stepper'];

/* Activation & deactivation repositories — paraphrased ideas in the spirit of
   the Intelligent Fitness bolt-ons. ~10 min before, ~10-15 min after. */
const ACTIVATION_IDEAS = [
  { name: 'Easy cardio, 10 min', text: 'Bike, row or jog at conversational pace. You are raising the heart rate and telling the body work is coming — not training yet.' },
  { name: 'Throw a ball around', text: 'Rugby ball, baseball, anything. Coordination, fun, and the moment to ask yourself: how did I sleep, any niggles, what do I want from today?' },
  { name: 'Skipping', text: '2–3 easy minutes. Rhythm, calves, coordination — a favourite pre-workout switch-on.' },
  { name: 'Dynamic mobility', text: 'Arm circles, leg swings, hip openers, torso rotations. Move every joint you are about to load through its range.' },
  { name: 'Pedal to standing', text: 'From the pike position (hands flat, hips high), pedal the feet one at a time, walk the feet toward the hands, and roll up to standing slowly. Wakes the calves and hamstrings.' },
  { name: 'Plank → pike → cobra', text: 'From a forearm plank, lift the hips to a pike, lower them until they hover, then come forward into a gentle cobra looking slightly up. Spine and abdominals ready.' },
  { name: 'Agility bursts', text: 'Sidesteps, a few light accelerations with controlled deceleration, ten seconds of fast feet. Prime the nervous system, especially before sprint or plyo work.' },
];

/* Concrete dynamic stretches — drawn from the 10-Weeks Wednesday sessions
   plus warm-up standards, filtered for a protected lower back. */
const ACTIVATION_STRETCHES = [
  { name: 'Bear crawl into pigeon', text: 'Hinge down, walk the hands out to a plank. Bring one knee forward and lower toward the floor at 90°, sink onto the forearms, then reach the arms long. Ease out, walk back, stand up. Per side — opens hips and glutes.' },
  { name: 'Bear crawl into cobra', text: 'Walk out to a plank, drop the hips and bring the chest forward into a gentle cobra, looking slightly up. Walk back to standing. Spine extension without load.' },
  { name: 'Reverse lunge + hip-flexor reach', text: 'Step back into a lunge, rear knee down, interlock the fingers and reach overhead with a slight lean back until the hip flexor stretches. Add a small forward-back rock. Per side — the tall-lifter essential.' },
  { name: 'Quad-stretch into reverse lunge', text: 'Standing quad stretch (heel to glute, hold ~30 s), release straight back into a reverse lunge with arms locked overhead, then rise and hug the knee to the chest. One flowing sequence per leg.' },
  { name: "World's greatest stretch", text: 'Long lunge, both hands inside the front foot. Drop the back knee, sink the hips, then rotate the inside arm up to the ceiling, following it with your eyes. Per side — hips, hamstrings and thoracic spine in one move.' },
  { name: 'Leg swings', text: 'Hold something stable. Swing one leg front-to-back 10-15 times, then side-to-side across the body. Loosens hips and hamstrings dynamically — no bouncing at end range.' },
  { name: 'Hip circles / openers', text: 'Standing, lift one knee and draw the biggest circle you can — inward rotations, then outward. Per side.' },
  { name: 'Cat-cow', text: 'On all fours, alternate slowly between rounding the spine up (cat) and letting it sink with the chest forward (cow), moving with the breath. Wakes up every spinal segment gently.' },
  { name: 'Thoracic openers (book drill)', text: 'Kneeling, thread one arm under the body then rotate it up to the ceiling, chest following. Per side. Upper-back rotation so the lower back does not have to provide it later.' },
  { name: 'Spinal mobility rock', text: 'On your back, hug both knees to the chest and rock gently forward and back, growing the range a little each rep. From the Wednesday sessions — a favourite before hinge days.' },
  { name: 'Glutes & piriformis (figure-4)', text: 'On your back, ankle over the opposite knee, clasp behind the thigh and pull toward you until the glute stretches. Per side.' },
  { name: 'Pedal to standing', text: 'Pike position, hands flat, pedal the heels one at a time, walk the feet to the hands and roll up slowly to standing. Calves and hamstrings switched on.' },
  { name: 'Side crab', text: 'In a low squat, crawl sideways a few steps, shoot the trailing leg out, return, and go back the other way. Animalistic movement — ankles, hips and coordination.' },
  { name: 'Upper-body matrix', text: 'Kneeling: cross-body shoulder pull, hands clasped behind the back with chest proud, triceps reach down the spine, wrist circles both ways, and a gentle side neck stretch. ~30 s each.' },
  { name: '90-90 hip switch', text: 'Sitting with both knees bent at 90°, one in front, one to the side, rotate the knees together over to the other side without using the hands. Internal + external hip rotation in one drill.' },
  { name: 'Ankle rockers', text: 'Half-kneeling, front foot flat about a hand-width from a wall. Drive the knee over the toes to touch the wall, heel stays down. Per side — squat depth lives in the ankles.' },
  { name: 'Goblet-squat prying', text: 'Hold the bottom of a light goblet squat and gently shift weight side to side, elbows prying the knees out. 30-45 s. Opens the hips exactly where the squat needs them.' },
];

const DEACTIVATION_IDEAS = [
  { name: 'Bring the heart rate down', text: 'Two or three minutes of easy movement — slow walk, light multidirectional steps. You are switching out of activity mode.' },
  { name: 'Stretch what you trained', text: 'Hold each stretch to a comfortable discomfort, wait for it to fade, then add roughly 10% more and hold again before easing off slowly. Control the exit as much as the entry — stretching marks the end of the session.' },
  { name: 'Breathing reset', text: 'Sit cross-legged, elbows on knees. Breathe into the lower third of the lungs, exhale fully. Ten to fifteen slow breaths — near-meditative, heart rate visibly drops.' },
  { name: 'Ten-second reactivation', text: 'Finish with a ten-second sprint on the spot. It sounds odd after calming down, but it leaves you invigorated for the rest of the day.' },
  { name: 'Refuel window', text: 'The best time to refuel is the 20–30 minutes after training: protein plus fluids. Prepare it before the session so it is waiting for you.' },
];

// measure: 'reps' (log reps + weight) | 'secs' (log seconds + weight)
// pattern: movement family -> pictogram in the Library and workout screens
const SEED_EXERCISES = [
  // legs
  { id: 'box_squat', name: 'Box squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Sit back to the box, drive up through heels',
    desc: 'Stand in front of a box, barbell or dumbbells racked. Sit back and down until you touch the box, then drive up through the heels without bouncing.' },
  { id: 'paused_box_squat', name: 'Paused box squat', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'squat',
    cue: '2s pause on the box, no bounce',
    desc: 'Like a box squat, but stay seated for two full seconds with tension on, then stand up explosively. Kills momentum — pure strength.' },
  { id: 'reverse_lunge', name: 'Reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Knee kisses the floor, per leg',
    desc: 'From standing, step one leg back and drop the rear knee until it just touches the floor. Push through the front heel to return. Count reps per leg.' },
  { id: 'deficit_reverse_lunge', name: 'Deficit reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Front foot on low plate, per leg',
    desc: 'Reverse lunge with the front foot standing on a low plate or step — the extra depth increases range of motion. Per leg.' },
  { id: 'goblet_squat', name: 'Goblet squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Elbows inside knees at depth',
    desc: 'Hold one dumbbell or kettlebell vertically against your chest, elbows tucked. Squat until your elbows brush the inside of your knees, stand tall.' },
  { id: 'trap_bar_deadlift', name: 'Trap bar deadlift', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'hinge',
    cue: 'Neutral grip, push the floor away, no rounding',
    desc: 'Stand inside the trap bar, neutral grip on the handles. Brace, keep the spine long, and push the floor away to stand tall. The centered load and high handles make it the back-friendliest heavy pull — your hinge anchor.' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian split squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Rear foot on bench, per leg',
    desc: 'Rear foot elevated on a bench behind you, front leg does the work. Lower until the front thigh is parallel, drive back up. Per leg.' },
  { id: 'lateral_lunge', name: 'Lateral lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Sit into the working hip, per leg',
    desc: 'Step wide to the side, sit back into that hip with the other leg straight, then push back to standing. Per leg.' },
  { id: 'romanian_deadlift', name: 'Romanian deadlift', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Hinge, soft knees, flat back',
    desc: 'Bar or dumbbells in front of the thighs. Push the hips back with soft knees, lowering the weight along the legs until the hamstrings load, then stand by squeezing the glutes.' },
  { id: 'single_leg_rdl', name: 'Single-leg RDL', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Square hips, per leg',
    desc: 'Balance on one leg, hinge forward as the free leg extends behind you, weight lowering toward the floor. Keep hips square. Per leg.' },
  { id: 'hip_thrust', name: 'Hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'Shoulders on bench, squeeze glutes at top',
    desc: 'Shoulder blades on a bench, feet planted, weight on the hips. Lower the glutes almost to the floor, then drive up until the torso is level, squeezing hard at the top.' },
  { id: 'single_leg_hip_thrust', name: 'Single-leg hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'One foot down, per leg',
    desc: 'Hip thrust with one foot on the floor and the other leg extended. All the load goes through one side. Per leg.' },
  { id: 'box_step_up', name: 'Box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Step up both feet, step down — never jump down',
    desc: 'Step onto a knee-high box with both feet, step back down leading with the opposite leg. Never jump down. Alternate the leading leg between sets.' },
  { id: 'lateral_box_step', name: 'Lateral box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Sideways to the box, per leg',
    desc: 'Stand sideways next to the box, step up with the near leg, bring the other up, and step down the far side or reverse. Per leg.' },
  { id: 'calf_raise', name: 'Calf raise', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Full stretch at bottom, pause at top',
    desc: 'Balls of the feet on an edge or plate, heels hanging. Drop into a full stretch, then rise as high as possible and pause a second at the top.' },
  { id: 'jump_squat', name: 'Jump squat', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Land soft, reset each rep',
    desc: 'Bodyweight squat into a vertical jump. Land soft with bent knees, reset your stance, repeat. Quality over speed.' },
  { id: 'band_lateral_walk', name: 'Band lateral walk', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Band above knees, small squat steps',
    desc: 'Mini-band just above the knees, quarter-squat stance. Take small side steps keeping constant tension on the band — count steps per direction.' },
  { id: 'band_matrix', name: 'Band matrix', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Side steps + forward/back, keep band tension',
    desc: 'With the band above the knees: side steps right and left, then small steps forward and back, never letting the band go slack. One full cycle = one rep.' },
  { id: 'wall_sit', name: 'Wall sit', group: 'legs', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Knees at 90°, back flat on wall',
    desc: 'Back flat against a wall, slide down until the knees are at 90° and hold. Add a plate on the thighs for load. Logged in seconds.' },
  // upper
  { id: 'pull_up', name: 'Pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Full hang to chin over bar',
    desc: 'Overhand grip on the bar, start from a full hang, pull until the chin clears the bar, lower with control. No kipping.' },
  { id: 'weighted_pull_up', name: 'Weighted pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Add belt/dumbbell, strict form',
    desc: 'Pull-up with added load — dip belt or a dumbbell between the feet. Strict form, full range. Log the added weight.' },
  { id: 'chin_up', name: 'Chin-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Underhand grip, full range',
    desc: 'Like a pull-up but with an underhand (palms toward you) grip — more biceps, slightly easier. Full hang to chin over bar.' },
  { id: 'lat_pulldown', name: 'Lat pulldown', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Pull to upper chest, control up',
    desc: 'At the cable station, pull the bar down to the upper chest with the chest proud, then let it rise with full control. No leaning back for momentum.' },
  { id: 'db_bench_press', name: 'DB bench press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Full range, elbows ~45°',
    desc: 'Lying on a flat bench with a dumbbell in each hand, press from chest level to lockout. Elbows about 45° from the torso, full range both ways.' },
  { id: 'bench_press', name: 'Bench press', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Bar to chest, feet planted',
    desc: 'Barbell bench: lower the bar to the chest under control, press to lockout. Feet planted, shoulder blades pinched. Use a spotter or safeties when heavy.' },
  { id: 'incline_db_press', name: 'Incline DB press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Bench ~30°, press up and slightly back',
    desc: 'Dumbbell press on a bench set to roughly 30° incline — shifts the work to the upper chest and shoulders.' },
  { id: 'push_up', name: 'Push-up', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Elbows to 90°, neutral back',
    desc: 'Hands shoulder-width, body in one line. Lower until the elbows reach 90°, press back up. On dumbbells for straighter wrists and extra depth.' },
  { id: 'overhead_press', name: 'Overhead press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Press strict, ribs down',
    desc: 'Standing, bar or dumbbells at the shoulders. Press strictly overhead to lockout without leaning back — brace the trunk, ribs down.' },
  { id: 'arnold_press', name: 'Arnold press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Rotate palms through the press',
    desc: 'Start with dumbbells at the shoulders, palms facing you. As you press up, rotate the palms to face forward; reverse on the way down.' },
  { id: 'bent_over_row', name: 'Bent-over row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Hinge, pull to lower ribs',
    desc: 'Hinge to roughly 45°, back flat. Row the bar or dumbbells to the lower ribs, squeezing the shoulder blades, then lower with control.' },
  { id: 'single_arm_row', name: 'Single-arm DB row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Knee on bench, per arm',
    desc: 'One knee and hand on the bench, flat back. Row the dumbbell to the hip in one strong arc without twisting the torso. Per arm.' },
  { id: 'chest_supported_row', name: 'Chest-supported DB row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Chest on incline bench, row both DBs',
    desc: 'Lie chest-down on an incline bench, a dumbbell in each hand. Row both to the hips, squeezing the shoulder blades. All the rowing, none of the lower-back load — the tall-lifter row.' },
  { id: 'shoulder_matrix', name: 'Shoulder matrix', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Lateral + front raises, soft elbows',
    desc: 'Light dumbbells: a set of lateral raises to shoulder height, straight into a set of front raises. Soft elbows, no swinging. One pair = one rep.' },
  { id: 'lateral_raise', name: 'Lateral raise', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'To shoulder height, no swing',
    desc: 'Dumbbells at the sides, raise the arms out to shoulder height with slightly bent elbows, lower slowly. Light weight, strict form.' },
  { id: 'dips', name: 'Dips', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Elbows to 90°, lean slightly forward',
    desc: 'On parallel bars, lower until the elbows hit 90° with a slight forward lean (more chest), then press back to lockout.' },
  { id: 'weighted_dip', name: 'Weighted dip', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Add weight, full depth',
    desc: 'Dips with a dip belt or dumbbell between the feet. Same full range — 90° elbows to lockout. Log the added weight.' },
  { id: 'cable_chest_fly', name: 'Cable chest fly (low-high)', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Split stance, soft elbows, cables to forehead',
    desc: 'Stand between low cables, back to the machine, split stance. With soft elbows sweep the handles up to forehead height, squeeze the chest two seconds, return.' },
  { id: 'face_pull', name: 'Face pull', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull',
    cue: 'Pull to face, elbows high',
    desc: 'Rope on a high cable. Pull toward the face with elbows high and wide, finishing with the hands beside the ears. Great for posture and rear shoulders.' },
  // core
  { id: 'ab_rollout', name: 'Ab rollout', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Roll out slow, no sag',
    desc: 'Kneeling with an ab wheel or loaded bar, roll forward as far as you can keep the hips from sagging, then pull back using the abs.' },
  { id: 'hanging_knee_raise', name: 'Hanging knee raise', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Knees to chest, no swing',
    desc: 'Hang from the pull-up bar, raise the knees to the chest without swinging, lower with control. Straight legs to progress.' },
  { id: 'plank_to_pike', name: 'Plank to pike', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Forearms down, hips up and back',
    desc: 'From a forearm plank, push the hips up and back into a pike, then return to a tight plank. Slow and controlled.' },
  { id: 'pallof_press', name: 'Pallof press', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Resist rotation, per side',
    desc: 'Cable or band at chest height, stand side-on. Press the handle straight out and back while resisting the pull to rotate. Per side.' },
  { id: 'v_up', name: 'V-up', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Hands to feet, control down',
    desc: 'Lying flat, fold up bringing straight arms and legs together into a V, then lower both with control without resting.' },
  { id: 'dead_bug', name: 'Dead bug', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Lower back pressed to floor, opposite arm + leg',
    desc: 'On your back, arms up, knees at 90°. Lower one arm and the opposite leg toward the floor while the lower back stays pressed down, then switch. Anti-extension core work with zero spine load. Per side.' },
  { id: 'bird_dog', name: 'Bird dog', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'On all fours, opposite arm + leg, no wobble',
    desc: 'On hands and knees, extend one arm and the opposite leg until level with the torso, hold a beat, return without letting the hips tilt. A McGill back-resilience staple. Per side.' },
  { id: 'mcgill_curl_up', name: 'McGill curl-up', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Hands under lower back, lift head + shoulders only',
    desc: 'On your back, one knee bent, hands under the natural arch of the lower back. Lift just the head and shoulders an inch, hold, lower. Trains the abs while the spine stays neutral — the back-safe crunch. Alternate the bent leg.' },
  { id: 'mountain_climbers', name: 'Mountain climbers', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Fast knees, flat back',
    desc: 'High plank, drive the knees toward the chest alternately as fast as clean form allows. Logged in seconds.' },
  { id: 'bear_crawl', name: 'Bear crawl', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Knees an inch off the floor',
    desc: 'On hands and toes, knees hovering an inch off the ground, crawl forward and back with opposite hand and foot moving together. Logged in seconds.' },
  // mixed / plyo / full-body
  { id: 'box_jump', name: 'Box jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Explode up, step down',
    desc: 'From standing, jump onto the box landing soft with both feet, stand tall, then STEP down — never jump down. Reset before every rep.' },
  { id: 'broad_jump', name: 'Broad jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Stick the landing, walk back',
    desc: 'Standing long jump: swing the arms, jump forward as far as you can, stick the landing in a quarter squat. Walk back, reset, repeat.' },
  { id: 'kb_swing', name: 'Kettlebell swing', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'swing',
    cue: 'Hips drive, arms relaxed',
    desc: 'Hinge and hike the kettlebell back, then snap the hips forward to float it to chest height. The hips do the work — the arms only guide.' },
  { id: 'kb_clean_press', name: 'KB clean & press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Clean to rack, press strict, per arm',
    desc: 'Swing the kettlebell up to the rack position at the shoulder (clean), then press it strictly overhead. Lower, repeat. Per arm.' },
  { id: 'thruster', name: 'Thruster', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Squat into overhead press, one motion',
    desc: 'Dumbbells at the shoulders, squat to depth, then drive up and press overhead in one continuous motion. Full body, big heart-rate spike.' },
  { id: 'db_snatch', name: 'DB snatch', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Floor to overhead, per arm',
    desc: 'One dumbbell from the floor to locked-out overhead in one explosive pull, using the hips. Lower to the floor, repeat. Per arm.' },
  { id: 'devil_press', name: 'Devil press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Burpee + double-DB snatch',
    desc: 'With two dumbbells: burpee with chest to the floor, then swing both dumbbells overhead in one motion as you stand. Brutal — pace yourself.' },
  { id: 'burpee', name: 'Burpee', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Chest to floor, jump at top',
    desc: 'Drop to the floor with chest touching, push up, jump the feet in, and finish with a small jump and full extension at the top.' },
  { id: 'sprawl', name: 'Sprawl', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Burpee without push-up or jump',
    desc: 'A faster burpee: throw the legs back to a plank, snap them back in, stand tall. No push-up, no jump — keep the pace high.' },
  { id: 'med_ball_slam', name: 'Med-ball slam', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'swing',
    cue: 'Full extension, slam hard',
    desc: 'Raise a medicine ball fully overhead, rise onto the toes, and slam it into the floor as hard as possible. Catch the bounce, repeat.' },
  { id: 'box_jump_over', name: 'Box jump-over', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Jump on, step over and down',
    desc: 'Jump onto the box, step over the top to the far side, step down, turn around, repeat. One crossing = one rep.' },
  { id: 'walking_lunge', name: 'Walking lunge', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Long steps, torso tall, total steps',
    desc: 'Lunge forward, knee kissing the floor, then step through into the next lunge — walking across the floor. Count total steps.' },
  { id: 'renegade_row', name: 'Renegade row', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Plank on DBs, row without twisting',
    desc: 'High plank with hands on two dumbbells. Row one dumbbell to the hip while the body stays dead level — no twisting. Alternate arms.' },
  { id: 'farmers_carry', name: "Farmer's carry", group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'Heavy DBs, tall posture',
    desc: 'Pick up the heaviest dumbbells you can hold safely and walk tall — shoulders back, no leaning. Logged in seconds.' },
  { id: 'suitcase_carry', name: 'Suitcase carry', group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'One-sided carry, stay level, per side',
    desc: "Farmer's carry with only one dumbbell — the core fights to keep you level. Swap sides halfway. Logged in seconds per side." },
  // travel: band + bodyweight library (1 long band with door anchor + 1 loop band)
  { id: 'band_squat', name: 'Band squat', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'squat',
    cue: 'Stand on the band, handles at shoulders',
    desc: 'Stand on the long band with both feet, handles racked at the shoulders. Squat to depth and drive up against the band. Log band level instead of kg.' },
  { id: 'split_squat', name: 'Split squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Static lunge stance, per leg',
    desc: 'Static lunge: one foot forward, one back, drop the rear knee to the floor and drive up. Rear foot on a chair for the Bulgarian version. Per leg.' },
  { id: 'band_rdl', name: 'Band RDL', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'hinge',
    cue: 'Stand on band, hinge against it',
    desc: 'Stand on the long band, handles at the thighs. Push the hips back with a flat back, then stand tall against the band tension, squeezing the glutes.' },
  { id: 'glute_bridge', name: 'Glute bridge', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'bridge',
    cue: 'Shoulders on floor, squeeze at top',
    desc: 'Lying on the floor, feet planted, drive the hips up until the body is one line from knees to shoulders. Pause and squeeze at the top. Loop band above the knees for extra work.' },
  { id: 'single_leg_glute_bridge', name: 'Single-leg glute bridge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'One foot down, per leg',
    desc: 'Glute bridge with one leg extended — all the load through one side. Hips stay level. Per leg.' },
  { id: 'band_row', name: 'Band row', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull',
    cue: 'Anchor at chest height, squeeze blades',
    desc: 'Long band anchored in the door at chest height (or around your feet, seated). Row the handles to the lower ribs, squeezing the shoulder blades together.' },
  { id: 'band_pulldown', name: 'Band pulldown', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull',
    cue: 'Anchor high, pull to chest',
    desc: 'Long band anchored at the top of the door. Kneel or sit, pull the handles down to the upper chest with the chest proud — the hotel-room pull-up.' },
  { id: 'band_pull_apart', name: 'Band pull-apart', group: 'upper', measure: 'reps', bucket: '17-20+', pattern: 'pull',
    cue: 'Arms straight, band to chest',
    desc: 'Hold the band at shoulder height with straight arms and pull it apart until it touches the chest. Rear shoulders and posture — the face-pull stand-in.' },
  { id: 'band_chest_press', name: 'Band chest press', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Band around the back, press forward',
    desc: 'Long band around the upper back, a handle in each hand. Press forward to full extension, control the return. Split stance for stability.' },
  { id: 'chair_dip', name: 'Chair dip', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Hands on chair edge, elbows to 90°',
    desc: 'Hands on the edge of a sturdy chair, legs extended in front. Lower until the elbows reach 90°, press back up. Bend the knees to make it easier.' },
  { id: 'band_overhead_press', name: 'Band overhead press', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'press',
    cue: 'Stand on band, press strict',
    desc: 'Stand on the long band, handles at the shoulders. Press strictly overhead against the band, ribs down, no lean-back.' },
  { id: 'band_lateral_raise', name: 'Band lateral raise', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Stand on band, raise to shoulder height',
    desc: 'Stand on the band, arms at the sides. Raise the handles out to shoulder height with soft elbows, lower slowly.' },
  { id: 'band_thruster', name: 'Band thruster', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'press',
    cue: 'Squat into overhead press, one motion',
    desc: 'Stand on the long band, handles at the shoulders. Squat to depth, then drive up and press overhead in one continuous motion — the hotel thruster.' },
  { id: 'walkout', name: 'Walkout', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Hands walk out to plank, no sag',
    desc: 'From standing, fold forward, walk the hands out to a long plank without letting the hips sag, then walk back and stand. The rollout without the wheel.' },
  { id: 'plank_hold', name: 'Plank hold', group: 'core', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'One straight line, braced',
    desc: 'Forearm plank: body one straight line from heels to head, glutes and abs braced. Logged in seconds.' },
  { id: 'side_plank', name: 'Side plank', group: 'core', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Hips high, per side',
    desc: 'On one forearm, body in a straight line, hips high. The anti-lean core work — the suitcase carry without the suitcase. Logged in seconds per side.' },
];

/* Travel mode: gym exercise -> band/bodyweight substitute (same movement pattern).
   Exercises not listed are already hotel-compatible and stay as they are. */
const TRAVEL_SUBS = {
  box_squat: 'band_squat', paused_box_squat: 'band_squat', goblet_squat: 'band_squat',
  trap_bar_deadlift: 'band_rdl',
  deficit_reverse_lunge: 'reverse_lunge', bulgarian_split_squat: 'split_squat',
  box_step_up: 'walking_lunge', lateral_box_step: 'lateral_lunge',
  romanian_deadlift: 'band_rdl',
  hip_thrust: 'glute_bridge', single_leg_hip_thrust: 'single_leg_glute_bridge',
  pull_up: 'band_pulldown', weighted_pull_up: 'band_pulldown', chin_up: 'band_pulldown', lat_pulldown: 'band_pulldown',
  bent_over_row: 'band_row', single_arm_row: 'band_row', renegade_row: 'band_row', chest_supported_row: 'band_row',
  face_pull: 'band_pull_apart',
  db_bench_press: 'push_up', bench_press: 'push_up', incline_db_press: 'push_up',
  cable_chest_fly: 'band_chest_press',
  dips: 'chair_dip', weighted_dip: 'chair_dip',
  overhead_press: 'band_overhead_press', arnold_press: 'band_overhead_press',
  shoulder_matrix: 'band_lateral_raise', lateral_raise: 'band_lateral_raise',
  ab_rollout: 'walkout', hanging_knee_raise: 'v_up',
  box_jump: 'jump_squat', broad_jump: 'jump_squat', box_jump_over: 'sprawl',
  kb_swing: 'jump_squat', kb_clean_press: 'band_thruster', thruster: 'band_thruster', db_snatch: 'band_thruster',
  devil_press: 'burpee', med_ball_slam: 'sprawl',
  farmers_carry: 'plank_hold', suitcase_carry: 'side_plank',
};

const TRAVEL_CARDIO = ['Skipping', 'Shadow boxing', 'Burpees', 'High knees', 'Stair runs'];
const TRAVEL_SPRINT_MODALITIES = ['Stair runs', 'Burpees', 'Shadow boxing', 'High knees'];

// Slot order = accumulator frequency: A done 5x per session, B 4x ... E 1x.
// A/B = anchor lifts. Weeks 1-3 (early) and 4-6 (late) blocks.
const SEED_BLOCKS = {
  early: {
    LEGS1:  ['box_squat', 'reverse_lunge', 'hip_thrust', 'box_step_up', 'band_lateral_walk'],
    UPPER1: ['pull_up', 'db_bench_press', 'overhead_press', 'chest_supported_row', 'ab_rollout'],
    MIXED1: ['box_jump', 'kb_swing', 'thruster', 'plank_to_pike', 'farmers_carry'],
    LEGS2:  ['trap_bar_deadlift', 'bulgarian_split_squat', 'goblet_squat', 'calf_raise', 'wall_sit'],
    UPPER2: ['incline_db_press', 'lat_pulldown', 'dips', 'shoulder_matrix', 'face_pull'],
    MIXED2: ['burpee', 'walking_lunge', 'renegade_row', 'med_ball_slam', 'mountain_climbers'],
  },
  late: {
    LEGS1:  ['paused_box_squat', 'deficit_reverse_lunge', 'single_leg_hip_thrust', 'lateral_box_step', 'band_matrix'],
    UPPER1: ['weighted_pull_up', 'bench_press', 'arnold_press', 'single_arm_row', 'hanging_knee_raise'],
    MIXED1: ['broad_jump', 'kb_clean_press', 'db_snatch', 'mcgill_curl_up', 'suitcase_carry'],
    LEGS2:  ['trap_bar_deadlift', 'lateral_lunge', 'single_leg_rdl', 'jump_squat', 'wall_sit'],
    UPPER2: ['weighted_dip', 'chin_up', 'cable_chest_fly', 'lateral_raise', 'pallof_press'],
    MIXED2: ['devil_press', 'box_jump_over', 'sprawl', 'dead_bug', 'bear_crawl'],
  },
};

const WEEK_PLAN = ['LEGS1', 'UPPER1', 'MIXED1', 'LEGS2', 'UPPER2', 'SPRINT', 'REST'];

function seedState() {
  const exercises = {};
  SEED_EXERCISES.forEach((e) => { exercises[e.id] = e; });
  return {
    version: STORE_VERSION,
    settings: { cardioMinutes: 2, fontScale: 1, weightStep: 2.5, travelMode: false },
    exercises,
    journeys: [{
      id: 'j1',
      name: 'Journey 1',
      startDate: new Date().toISOString().slice(0, 10),
      weekCount: 6,
      weekPlan: WEEK_PLAN.slice(),
      blocks: JSON.parse(JSON.stringify(SEED_BLOCKS)),
    }],
    activeJourneyId: 'j1',
    sessions: [],
    zone2Checks: {},
    current: null,
  };
}

function blockForWeek(week) { return week <= 3 ? 'early' : 'late'; }
