/* data.js — exercise library + seed journey (Waterson 5-2 accumulator, adapted) */

const BUCKETS = ['6-8', '9-12', '13-16', '17-20+'];

const CARDIO_MODALITIES = [
  'Run / Sprints', 'Bike', 'Row', 'SkiErg',
  'Heavy bag', 'Battle ropes', 'Skipping', 'Plyo circuit',
];

const ZONE2_MODALITIES = ['Bike', 'Run', 'Row', 'Walk / Hike', 'SkiErg', 'Swim'];

const DAY_TYPES = {
  LEGS1:  { label: 'Legs 1',  kind: 'legs' },
  UPPER1: { label: 'Upper 1', kind: 'upper' },
  SPRINT: { label: 'Sprint',  kind: 'sprint' },
  LEGS2:  { label: 'Legs 2',  kind: 'legs' },
  UPPER2: { label: 'Upper 2', kind: 'upper' },
  MIXED1: { label: 'Mixed',   kind: 'mixed' },
  REST:   { label: 'Rest',    kind: 'rest' },
  // legacy types (v1 journeys / old journal entries)
  MIXED2: { label: 'Mixed 2', kind: 'mixed' },
  ZONE2:  { label: 'Zone 2',  kind: 'zone2' },
};

const SPRINT_MODALITIES = ['Run / Track', 'Bike', 'Row', 'SkiErg'];

/* Activation & deactivation repositories — paraphrased ideas in the spirit of
   the Intelligent Fitness bolt-ons. ~10 min before, ~10-15 min after. */
const ACTIVATION_IDEAS = [
  { name: 'Easy cardio, 10 min', text: 'Bike, row or jog at conversational pace. You are raising the heart rate and telling the body work is coming — not training yet.' },
  { name: 'Throw a ball around', text: 'Rugby ball, baseball, anything. Coordination, fun, and the moment to ask yourself: how did I sleep, any niggles, what do I want from today?' },
  { name: 'Skipping', text: '2–3 easy minutes. Rhythm, calves, coordination — a favourite pre-workout switch-on.' },
  { name: 'Dynamic mobility', text: 'Arm circles, leg swings, hip openers, torso rotations. Move every joint you are about to load through its range.' },
  { name: 'Pedal to standing', text: 'From the pike position (hands flat, hips high), pedal the feet one at a time, walk the feet toward the hands, and roll up to standing slowly. Wakes the calves and hamstrings.' },
  { name: 'Plank → pike → cobra', text: 'From a forearm plank, lift the hips to a pike, lower them until they hover, then come forward into a gentle cobra looking slightly up. Spine and abdominals ready.' },
  { name: 'Agility bursts', text: 'Sidesteps, a few light accelerations with controlled deceleration, ten seconds of fast feet. Prime the nervous system, especially before sprint or plyo work.' },
];

const DEACTIVATION_IDEAS = [
  { name: 'Bring the heart rate down', text: 'Two or three minutes of easy movement — slow walk, light multidirectional steps. You are switching out of activity mode.' },
  { name: 'Stretch what you trained', text: 'Hold each stretch to a comfortable discomfort, wait for it to fade, then add roughly 10% more and hold again before easing off slowly. Control the exit as much as the entry — stretching marks the end of the session.' },
  { name: 'Breathing reset', text: 'Sit cross-legged, elbows on knees. Breathe into the lower third of the lungs, exhale fully. Ten to fifteen slow breaths — near-meditative, heart rate visibly drops.' },
  { name: 'Ten-second reactivation', text: 'Finish with a ten-second sprint on the spot. It sounds odd after calming down, but it leaves you invigorated for the rest of the day.' },
  { name: 'Refuel window', text: 'The best time to refuel is the 20–30 minutes after training: protein plus fluids. Prepare it before the session so it is waiting for you.' },
];

// measure: 'reps' (log reps + weight) | 'secs' (log seconds + weight)
// pattern: movement family -> pictogram in the Library and workout screens
const SEED_EXERCISES = [
  // legs
  { id: 'box_squat', name: 'Box squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Sit back to the box, drive up through heels',
    desc: 'Stand in front of a box, barbell or dumbbells racked. Sit back and down until you touch the box, then drive up through the heels without bouncing.' },
  { id: 'paused_box_squat', name: 'Paused box squat', group: 'legs', measure: 'reps', bucket: '6-8', pattern: 'squat',
    cue: '2s pause on the box, no bounce',
    desc: 'Like a box squat, but stay seated for two full seconds with tension on, then stand up explosively. Kills momentum — pure strength.' },
  { id: 'reverse_lunge', name: 'Reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Knee kisses the floor, per leg',
    desc: 'From standing, step one leg back and drop the rear knee until it just touches the floor. Push through the front heel to return. Count reps per leg.' },
  { id: 'deficit_reverse_lunge', name: 'Deficit reverse lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Front foot on low plate, per leg',
    desc: 'Reverse lunge with the front foot standing on a low plate or step — the extra depth increases range of motion. Per leg.' },
  { id: 'goblet_squat', name: 'Goblet squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Elbows inside knees at depth',
    desc: 'Hold one dumbbell or kettlebell vertically against your chest, elbows tucked. Squat until your elbows brush the inside of your knees, stand tall.' },
  { id: 'db_front_squat', name: 'DB front squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'squat',
    cue: 'Dumbbells racked at shoulders',
    desc: 'One dumbbell on each shoulder, elbows high. Squat to depth keeping the torso upright — the front load forces a strong upper back.' },
  { id: 'bulgarian_split_squat', name: 'Bulgarian split squat', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Rear foot on bench, per leg',
    desc: 'Rear foot elevated on a bench behind you, front leg does the work. Lower until the front thigh is parallel, drive back up. Per leg.' },
  { id: 'lateral_lunge', name: 'Lateral lunge', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'lunge',
    cue: 'Sit into the working hip, per leg',
    desc: 'Step wide to the side, sit back into that hip with the other leg straight, then push back to standing. Per leg.' },
  { id: 'romanian_deadlift', name: 'Romanian deadlift', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Hinge, soft knees, flat back',
    desc: 'Bar or dumbbells in front of the thighs. Push the hips back with soft knees, lowering the weight along the legs until the hamstrings load, then stand by squeezing the glutes.' },
  { id: 'single_leg_rdl', name: 'Single-leg RDL', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'hinge',
    cue: 'Square hips, per leg',
    desc: 'Balance on one leg, hinge forward as the free leg extends behind you, weight lowering toward the floor. Keep hips square. Per leg.' },
  { id: 'hip_thrust', name: 'Hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'Shoulders on bench, squeeze glutes at top',
    desc: 'Shoulder blades on a bench, feet planted, weight on the hips. Lower the glutes almost to the floor, then drive up until the torso is level, squeezing hard at the top.' },
  { id: 'single_leg_hip_thrust', name: 'Single-leg hip thrust', group: 'legs', measure: 'reps', bucket: '9-12', pattern: 'bridge',
    cue: 'One foot down, per leg',
    desc: 'Hip thrust with one foot on the floor and the other leg extended. All the load goes through one side. Per leg.' },
  { id: 'box_step_up', name: 'Box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Step up both feet, step down — never jump down',
    desc: 'Step onto a knee-high box with both feet, step back down leading with the opposite leg. Never jump down. Alternate the leading leg between sets.' },
  { id: 'lateral_box_step', name: 'Lateral box step-up', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Sideways to the box, per leg',
    desc: 'Stand sideways next to the box, step up with the near leg, bring the other up, and step down the far side or reverse. Per leg.' },
  { id: 'calf_raise', name: 'Calf raise', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Full stretch at bottom, pause at top',
    desc: 'Balls of the feet on an edge or plate, heels hanging. Drop into a full stretch, then rise as high as possible and pause a second at the top.' },
  { id: 'jump_squat', name: 'Jump squat', group: 'legs', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Land soft, reset each rep',
    desc: 'Bodyweight squat into a vertical jump. Land soft with bent knees, reset your stance, repeat. Quality over speed.' },
  { id: 'band_lateral_walk', name: 'Band lateral walk', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Band above knees, small squat steps',
    desc: 'Mini-band just above the knees, quarter-squat stance. Take small side steps keeping constant tension on the band — count steps per direction.' },
  { id: 'band_matrix', name: 'Band matrix', group: 'legs', measure: 'reps', bucket: '17-20+', pattern: 'band',
    cue: 'Side steps + forward/back, keep band tension',
    desc: 'With the band above the knees: side steps right and left, then small steps forward and back, never letting the band go slack. One full cycle = one rep.' },
  { id: 'wall_sit', name: 'Wall sit', group: 'legs', measure: 'secs', bucket: null, pattern: 'hold',
    cue: 'Knees at 90°, back flat on wall',
    desc: 'Back flat against a wall, slide down until the knees are at 90° and hold. Add a plate on the thighs for load. Logged in seconds.' },
  // upper
  { id: 'pull_up', name: 'Pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Full hang to chin over bar',
    desc: 'Overhand grip on the bar, start from a full hang, pull until the chin clears the bar, lower with control. No kipping.' },
  { id: 'weighted_pull_up', name: 'Weighted pull-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Add belt/dumbbell, strict form',
    desc: 'Pull-up with added load — dip belt or a dumbbell between the feet. Strict form, full range. Log the added weight.' },
  { id: 'chin_up', name: 'Chin-up', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'pull',
    cue: 'Underhand grip, full range',
    desc: 'Like a pull-up but with an underhand (palms toward you) grip — more biceps, slightly easier. Full hang to chin over bar.' },
  { id: 'lat_pulldown', name: 'Lat pulldown', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Pull to upper chest, control up',
    desc: 'At the cable station, pull the bar down to the upper chest with the chest proud, then let it rise with full control. No leaning back for momentum.' },
  { id: 'db_bench_press', name: 'DB bench press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Full range, elbows ~45°',
    desc: 'Lying on a flat bench with a dumbbell in each hand, press from chest level to lockout. Elbows about 45° from the torso, full range both ways.' },
  { id: 'bench_press', name: 'Bench press', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Bar to chest, feet planted',
    desc: 'Barbell bench: lower the bar to the chest under control, press to lockout. Feet planted, shoulder blades pinched. Use a spotter or safeties when heavy.' },
  { id: 'incline_db_press', name: 'Incline DB press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Bench ~30°, press up and slightly back',
    desc: 'Dumbbell press on a bench set to roughly 30° incline — shifts the work to the upper chest and shoulders.' },
  { id: 'push_up', name: 'Push-up', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Elbows to 90°, neutral back',
    desc: 'Hands shoulder-width, body in one line. Lower until the elbows reach 90°, press back up. On dumbbells for straighter wrists and extra depth.' },
  { id: 'overhead_press', name: 'Overhead press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Press strict, ribs down',
    desc: 'Standing, bar or dumbbells at the shoulders. Press strictly overhead to lockout without leaning back — brace the trunk, ribs down.' },
  { id: 'arnold_press', name: 'Arnold press', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Rotate palms through the press',
    desc: 'Start with dumbbells at the shoulders, palms facing you. As you press up, rotate the palms to face forward; reverse on the way down.' },
  { id: 'bent_over_row', name: 'Bent-over row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Hinge, pull to lower ribs',
    desc: 'Hinge to roughly 45°, back flat. Row the bar or dumbbells to the lower ribs, squeezing the shoulder blades, then lower with control.' },
  { id: 'single_arm_row', name: 'Single-arm DB row', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Knee on bench, per arm',
    desc: 'One knee and hand on the bench, flat back. Row the dumbbell to the hip in one strong arc without twisting the torso. Per arm.' },
  { id: 'shoulder_matrix', name: 'Shoulder matrix', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'Lateral + front raises, soft elbows',
    desc: 'Light dumbbells: a set of lateral raises to shoulder height, straight into a set of front raises. Soft elbows, no swinging. One pair = one rep.' },
  { id: 'lateral_raise', name: 'Lateral raise', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'raise',
    cue: 'To shoulder height, no swing',
    desc: 'Dumbbells at the sides, raise the arms out to shoulder height with slightly bent elbows, lower slowly. Light weight, strict form.' },
  { id: 'dips', name: 'Dips', group: 'upper', measure: 'reps', bucket: '9-12', pattern: 'push',
    cue: 'Elbows to 90°, lean slightly forward',
    desc: 'On parallel bars, lower until the elbows hit 90° with a slight forward lean (more chest), then press back to lockout.' },
  { id: 'weighted_dip', name: 'Weighted dip', group: 'upper', measure: 'reps', bucket: '6-8', pattern: 'push',
    cue: 'Add weight, full depth',
    desc: 'Dips with a dip belt or dumbbell between the feet. Same full range — 90° elbows to lockout. Log the added weight.' },
  { id: 'cable_chest_fly', name: 'Cable chest fly (low-high)', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'push',
    cue: 'Split stance, soft elbows, cables to forehead',
    desc: 'Stand between low cables, back to the machine, split stance. With soft elbows sweep the handles up to forehead height, squeeze the chest two seconds, return.' },
  { id: 'face_pull', name: 'Face pull', group: 'upper', measure: 'reps', bucket: '13-16', pattern: 'pull',
    cue: 'Pull to face, elbows high',
    desc: 'Rope on a high cable. Pull toward the face with elbows high and wide, finishing with the hands beside the ears. Great for posture and rear shoulders.' },
  // core
  { id: 'ab_rollout', name: 'Ab rollout', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Roll out slow, no sag',
    desc: 'Kneeling with an ab wheel or loaded bar, roll forward as far as you can keep the hips from sagging, then pull back using the abs.' },
  { id: 'hanging_knee_raise', name: 'Hanging knee raise', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Knees to chest, no swing',
    desc: 'Hang from the pull-up bar, raise the knees to the chest without swinging, lower with control. Straight legs to progress.' },
  { id: 'plank_to_pike', name: 'Plank to pike', group: 'core', measure: 'reps', bucket: '9-12', pattern: 'core',
    cue: 'Forearms down, hips up and back',
    desc: 'From a forearm plank, push the hips up and back into a pike, then return to a tight plank. Slow and controlled.' },
  { id: 'pallof_press', name: 'Pallof press', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Resist rotation, per side',
    desc: 'Cable or band at chest height, stand side-on. Press the handle straight out and back while resisting the pull to rotate. Per side.' },
  { id: 'v_up', name: 'V-up', group: 'core', measure: 'reps', bucket: '13-16', pattern: 'core',
    cue: 'Hands to feet, control down',
    desc: 'Lying flat, fold up bringing straight arms and legs together into a V, then lower both with control without resting.' },
  { id: 'russian_twist', name: 'Russian twist', group: 'core', measure: 'reps', bucket: '17-20+', pattern: 'core',
    cue: 'Heels light, rotate through torso',
    desc: 'Seated, leaning back with heels light on the floor, rotate a plate or dumbbell side to side. Left+right = one rep.' },
  { id: 'mountain_climbers', name: 'Mountain climbers', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Fast knees, flat back',
    desc: 'High plank, drive the knees toward the chest alternately as fast as clean form allows. Logged in seconds.' },
  { id: 'bear_crawl', name: 'Bear crawl', group: 'core', measure: 'secs', bucket: null, pattern: 'core',
    cue: 'Knees an inch off the floor',
    desc: 'On hands and toes, knees hovering an inch off the ground, crawl forward and back with opposite hand and foot moving together. Logged in seconds.' },
  // mixed / plyo / full-body
  { id: 'box_jump', name: 'Box jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Explode up, step down',
    desc: 'From standing, jump onto the box landing soft with both feet, stand tall, then STEP down — never jump down. Reset before every rep.' },
  { id: 'broad_jump', name: 'Broad jump', group: 'mixed', measure: 'reps', bucket: '6-8', pattern: 'jump',
    cue: 'Stick the landing, walk back',
    desc: 'Standing long jump: swing the arms, jump forward as far as you can, stick the landing in a quarter squat. Walk back, reset, repeat.' },
  { id: 'kb_swing', name: 'Kettlebell swing', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'swing',
    cue: 'Hips drive, arms relaxed',
    desc: 'Hinge and hike the kettlebell back, then snap the hips forward to float it to chest height. The hips do the work — the arms only guide.' },
  { id: 'kb_clean_press', name: 'KB clean & press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Clean to rack, press strict, per arm',
    desc: 'Swing the kettlebell up to the rack position at the shoulder (clean), then press it strictly overhead. Lower, repeat. Per arm.' },
  { id: 'thruster', name: 'Thruster', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'press',
    cue: 'Squat into overhead press, one motion',
    desc: 'Dumbbells at the shoulders, squat to depth, then drive up and press overhead in one continuous motion. Full body, big heart-rate spike.' },
  { id: 'db_snatch', name: 'DB snatch', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'swing',
    cue: 'Floor to overhead, per arm',
    desc: 'One dumbbell from the floor to locked-out overhead in one explosive pull, using the hips. Lower to the floor, repeat. Per arm.' },
  { id: 'devil_press', name: 'Devil press', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Burpee + double-DB snatch',
    desc: 'With two dumbbells: burpee with chest to the floor, then swing both dumbbells overhead in one motion as you stand. Brutal — pace yourself.' },
  { id: 'burpee', name: 'Burpee', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Chest to floor, jump at top',
    desc: 'Drop to the floor with chest touching, push up, jump the feet in, and finish with a small jump and full extension at the top.' },
  { id: 'sprawl', name: 'Sprawl', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'jump',
    cue: 'Burpee without push-up or jump',
    desc: 'A faster burpee: throw the legs back to a plank, snap them back in, stand tall. No push-up, no jump — keep the pace high.' },
  { id: 'med_ball_slam', name: 'Med-ball slam', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'swing',
    cue: 'Full extension, slam hard',
    desc: 'Raise a medicine ball fully overhead, rise onto the toes, and slam it into the floor as hard as possible. Catch the bounce, repeat.' },
  { id: 'box_jump_over', name: 'Box jump-over', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'jump',
    cue: 'Jump on, step over and down',
    desc: 'Jump onto the box, step over the top to the far side, step down, turn around, repeat. One crossing = one rep.' },
  { id: 'walking_lunge', name: 'Walking lunge', group: 'mixed', measure: 'reps', bucket: '13-16', pattern: 'lunge',
    cue: 'Long steps, torso tall, total steps',
    desc: 'Lunge forward, knee kissing the floor, then step through into the next lunge — walking across the floor. Count total steps.' },
  { id: 'renegade_row', name: 'Renegade row', group: 'mixed', measure: 'reps', bucket: '9-12', pattern: 'pull',
    cue: 'Plank on DBs, row without twisting',
    desc: 'High plank with hands on two dumbbells. Row one dumbbell to the hip while the body stays dead level — no twisting. Alternate arms.' },
  { id: 'farmers_carry', name: "Farmer's carry", group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'Heavy DBs, tall posture',
    desc: 'Pick up the heaviest dumbbells you can hold safely and walk tall — shoulders back, no leaning. Logged in seconds.' },
  { id: 'suitcase_carry', name: 'Suitcase carry', group: 'mixed', measure: 'secs', bucket: null, pattern: 'carry',
    cue: 'One-sided carry, stay level, per side',
    desc: "Farmer's carry with only one dumbbell — the core fights to keep you level. Swap sides halfway. Logged in seconds per side." },
];

// Slot order = accumulator frequency: A done 5x per session, B 4x ... E 1x.
// A/B = anchor lifts. Weeks 1-3 (early) and 4-6 (late) blocks.
const SEED_BLOCKS = {
  early: {
    LEGS1:  ['box_squat', 'reverse_lunge', 'hip_thrust', 'box_step_up', 'band_lateral_walk'],
    UPPER1: ['pull_up', 'db_bench_press', 'overhead_press', 'bent_over_row', 'ab_rollout'],
    MIXED1: ['box_jump', 'kb_swing', 'thruster', 'plank_to_pike', 'farmers_carry'],
    LEGS2:  ['goblet_squat', 'bulgarian_split_squat', 'romanian_deadlift', 'calf_raise', 'wall_sit'],
    UPPER2: ['incline_db_press', 'lat_pulldown', 'dips', 'shoulder_matrix', 'face_pull'],
    MIXED2: ['burpee', 'walking_lunge', 'renegade_row', 'med_ball_slam', 'mountain_climbers'],
  },
  late: {
    LEGS1:  ['paused_box_squat', 'deficit_reverse_lunge', 'single_leg_hip_thrust', 'lateral_box_step', 'band_matrix'],
    UPPER1: ['weighted_pull_up', 'bench_press', 'arnold_press', 'single_arm_row', 'hanging_knee_raise'],
    MIXED1: ['broad_jump', 'kb_clean_press', 'db_snatch', 'v_up', 'suitcase_carry'],
    LEGS2:  ['db_front_squat', 'lateral_lunge', 'single_leg_rdl', 'jump_squat', 'wall_sit'],
    UPPER2: ['weighted_dip', 'chin_up', 'cable_chest_fly', 'lateral_raise', 'pallof_press'],
    MIXED2: ['devil_press', 'box_jump_over', 'sprawl', 'russian_twist', 'bear_crawl'],
  },
};

const WEEK_PLAN = ['LEGS1', 'UPPER1', 'SPRINT', 'LEGS2', 'UPPER2', 'MIXED1', 'REST'];

function seedState() {
  const exercises = {};
  SEED_EXERCISES.forEach((e) => { exercises[e.id] = e; });
  return {
    version: STORE_VERSION,
    settings: { cardioMinutes: 2, fontScale: 1, weightStep: 2.5 },
    exercises,
    journeys: [{
      id: 'j1',
      name: 'Journey 1',
      startDate: new Date().toISOString().slice(0, 10),
      weekCount: 6,
      weekPlan: WEEK_PLAN.slice(),
      blocks: JSON.parse(JSON.stringify(SEED_BLOCKS)),
    }],
    activeJourneyId: 'j1',
    sessions: [],
    zone2Checks: {},
    current: null,
  };
}

function blockForWeek(week) { return week <= 3 ? 'early' : 'late'; }
